# Generated by Django 2.1.7 on 2019-03-31 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_id', models.IntegerField()),
            ],
            options={
                'ordering': ('task_id',),
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('machine_id', models.AutoField(primary_key=True, serialize=False)),
                ('machine_name', models.CharField(blank=True, default='', max_length=100)),
                ('machine_type', models.IntegerField()),
                ('readiness', models.TextField(blank=True)),
            ],
            options={
                'ordering': ('machine_id',),
            },
        ),
    ]
