# Generated by Django 2.1.7 on 2019-03-31 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_tasks_vehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainGraph',
            fields=[
                ('point_id', models.AutoField(primary_key=True, serialize=False)),
                ('point_type', models.CharField(choices=[('D', 'Depot'), ('L', 'Location')], default='L', max_length=1)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
            options={
                'ordering': ('point_id',),
            },
        ),
        migrations.CreateModel(
            name='TaskPoints',
            fields=[
                ('itinerary_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_num', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('point_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.MainGraph')),
            ],
            options={
                'ordering': ('itinerary_id',),
            },
        ),
        migrations.DeleteModel(
            name='Snippet',
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_status_cd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='task_type_cd',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='machine_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Vehicle'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='machine_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='readiness',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='taskpoints',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Tasks'),
        ),
    ]
